### ISSUE TITLE
small issues 

### ISSUE THREAD

**Issue by slk333** [5t3ph/moderncss-dot-dev#14]
Hi!, noticed a markdown issue in https://moderncss.dev/guide-to-advanced-css-selectors-part-one/, the conclusion of the article has a markdown issue that doesn't render the link as it should. 

[Continue to part two where we'll learn about pseudo classes and pseudo elements]((https://moderncss.dev/guide-to-advanced-css-selectors-part-two/).

also a typo in https://moderncss.dev/guide-to-advanced-css-selectors-part-two/  article "The :visited pseduo class"

Thx for those articles, cheers

**Comment by 5t3ph** [comment]
@slk333 - thanks, these are fixed now
