### ISSUE TITLE
Header bug in Firefox?

### ISSUE THREAD

**Issue by CapyTheBeara** [5t3ph/moderncss-dot-dev#33]
Just found https://moderncss.dev/ today. So much awesomeness!

Anyways, I notice in Firefox 107.0.1 on Mac, that the "M" in your `<h1>` wasn't showing up
<img width="1253" alt="Screen Shot 2022-12-08 at 5 56 18 AM" src="https://user-images.githubusercontent.com/314922/206466079-461c7255-289f-4a67-9c71-8bdcdd73e178.png">

I tried to see if it was something with my Firefox settings, but couldn't find anything, but it did get fixed with turning off `-webkit-text-fill-color`. 
<img width="872" alt="image" src="https://user-images.githubusercontent.com/314922/206466806-5700de99-2ef1-41e1-8db2-72124839314a.png">

Something else weird happens with the `<h1>` when refreshing the page which seems to also be related to `-webkit-text-fill-color`. 
<img width="1266" alt="image" src="https://user-images.githubusercontent.com/314922/206467786-cba0cf13-9a73-4d32-aec9-8e0758210904.png">

Seems like a Firefox bug, but just wanted to let you know.

Thanks again for all your great content!

**Comment by Is0bel** [comment]
I have the same _bug_ with Firefox Developer Edition 109.0b7 on Windows, and wanted to express exactly the same considerations above. Besides, I only noticed that turning off -webkit-text-fill-color causes, in other browsers, the text to get heavier..

Anyway, thanks to Stephanie Eckles for her contents, that I've red and appreciated greatly for years.

**Comment by 5t3ph** [comment]
Hi all - thanks for your patience! I finally took a minute to hopefully fix this. It seems it was necessary to duplicate the gradient styles on the `::first-letter` and not rely on inheritance for it to work in Firefox.

Let me know a version if you still see that it's missing, thanks!
