### ISSUE TITLE
Feature suggestion: RSS feed

### ISSUE THREAD

**Issue by Alex-K1m** [5t3ph/moderncss-dot-dev#4]
Hello, Stephanie!
I would like to be able to subscribe to ModernCss.
The blog is amazing and very informative, thank you for sharing your knowledge, it helps me a lot.

**Comment by 5t3ph** [comment]
Hi @Alex-K1m - I'm glad you're enjoying the content! I have it on my list to add, I'll post back when it's complete!

**Comment by 5t3ph** [comment]
The feed is now ready!

https://moderncss.dev/feed/
